### ISSUE TITLE
1.12 Crashes on Start

### ISSUE THREAD

**Issue by iarna** [psiberx/cp2077-codeware#22]
Version of Cyberpunk is 2.12a via GOG, with Phantom Liberty and REDMod. Cyberpunk was reinstalled before testing. This crash does not happen with 1.11.2.

Codeware is clearly loading as evidenced by the log file. The log files do not seem to report any errors.

Mods installed:
- red4ext: 1.25
- Codeware: 1.12

Edit: I've also tried with 1.12.1 and it crashes in the same way.

Logs:
- Codeware log: [Codeware-2024-08-01-16-15-43.log](https://github.com/user-attachments/files/16461550/Codeware-2024-08-01-16-15-43.log)
- red4ext log: [red4ext-2024-08-01-16-15-42.log](https://github.com/user-attachments/files/16461548/red4ext-2024-08-01-16-15-42.log)
- CDPR Crash Report: [Cyberpunk2077-20240801-161550-11552-46736.zip](https://github.com/user-attachments/files/16461535/Cyberpunk2077-20240801-161550-11552-46736.zip)

**Comment by psiberx** [comment]
Hi. You have to install redscript. I'll make it so Codeware doesn't crash without redscript in the next update.

**Comment by iarna** [comment]
a redscript dep is fine, it just wasn't listed on the mod page
