### ISSUE TITLE
Codeware makes quickhacks crash my game

### ISSUE THREAD

**Issue by drovumas** [psiberx/cp2077-codeware#24]
As the title says, whenever i use quickhacks in the game, the game will crash, been experiencing this after remodding and all and going through the tutorial (which I'm still stuck behind the door for) 

[2024-09-14 19:41:22.712] [info] Codeware 1.12.7 is initializing...
[2024-09-14 19:41:23.149] [info] [ResourcePathRegistry] Loading metadata...
[2024-09-14 19:41:23.371] [info] [ResourcePathRegistry] Loaded 122143 predefined hashes.
[2024-09-14 19:41:23.429] [info] Codeware is initialized.
[2024-09-14 19:41:29.987] [debug] 7FF69F995D98 3345D98

CrashInfo.json

{
	"RootType": "gameTelemetryPostMortemContainer",
	"Data": {
		"postMortem": {
			"crashVisitId": "1398aabf-125d-4409-b866-fe9220eac23f",
			"playthroughId": "66e45b3d68cafbb6",
			"crashVersion": "5110895",
			"crashPatch": "2.13",
			"timeCrash": "2024-09-14T17:43:04Z",
			"trackedQuest": {
				"name": "q001_intro",
				"objectiveName": "get_to_apartment",
				"type": "Q",
				"distance": 3.000000,
				"questName": "",
				"questType": ""
			},
			"location": {
				"X": -466.099182,
				"Y": 374.943146,
				"Z": 133.600159
			},
			"district": "JapanTown",
			"zoneType": "",
			"sessionLength": 79.484001,
			"isOom": false
		}
	}
}

really don't know what you need, this is what i believe you do however.

**Comment by psiberx** [comment]
Why do you think it's related to Codeware?

**Comment by drovumas** [comment]
Because it, out of all mods, as the only enabled, crashes my game consistently when using quickhacks.

**Comment by psiberx** [comment]
The proper test would be to try using quickhacks with only Codeware and no other mods.

**Comment by drovumas** [comment]
Yeah now I'm very fucking confused, went through that and found out it was native settings UI instead, guess i wrongly diagnosed the culprit. Sorry man.

**Comment by psiberx** [comment]
To be honest I wouldn't expect Native Settings UI to cause something like that. Maybe it's actually a third mod that relies on both Native Settings UI and Codeware?

**Comment by drovumas** [comment]
Found out it was cyberscript core
