### ISSUE TITLE
Feature Request: Scriptable weather interface

### ISSUE THREAD

**Issue by nullfrctl** [psiberx/cp2077-codeware#9]
This is the one thing no framework has undertaken: weather.

It would be very useful to be able to trigger weather at any time, it could lead to custom weather cycles that can be configured in real time i.e.

It would especially be useful for any quest mods to trigger a weather in a scriptable manner.

**Comment by psiberx** [comment]
What parameters you'd expect for function to set current weather?

**Comment by psiberx** [comment]
Added in 1.3.1.

**Comment by nullfrctl** [comment]
Can Codeware (or any other framework) _get_ the current weather?
I'm currently brainstorming setting INI settings per-weather to have in-depth lighting customization; but I can't see a way to get the current weather.

Would this be better here or in a new issue?

**Comment by psiberx** [comment]
Do you mean weather name or definition?

**Comment by nullfrctl** [comment]
Weather name'd be enough; although I am interested in what this "definition" mean specifically&hellip;
